apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: spark-master
  name: spark-master  
spec:
  replicas: 1
  selector:
    name: spark-master
  template:
    metadata:
      labels:
        name: spark-master
    spec:
      containers:
      - image: cacidocker-caciuk.azurecr.io/caci-main/spark-master:latest
        name: spark-master              
        ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
        - containerPort: 7077
          hostPort: 7077
          protocol: TCP
        - containerPort: 9000
          hostPort: 9000
          protocol: TCP
        - containerPort: 50070
          hostPort: 50070
          protocol: TCP      
      imagePullSecrets:
        - name: myregistrykey